# Generated by Django 5.1.2 on 2025-12-08 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PresentationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("current_slide", models.IntegerField(default=0)),
                ("total_slides", models.IntegerField(default=0)),
                ("is_fullscreen", models.BooleanField(default=False)),
                ("is_presenting", models.BooleanField(default=False)),
                ("avg_latency_ms", models.FloatField(default=0.0)),
                ("gesture_count", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fps", models.FloatField(default=0.0)),
                ("latency_ms", models.FloatField(default=0.0)),
                ("cpu_usage", models.FloatField(blank=True, null=True)),
                ("memory_usage_mb", models.FloatField(blank=True, null=True)),
                ("false_positives", models.IntegerField(default=0)),
                ("false_negatives", models.IntegerField(default=0)),
                ("true_positives", models.IntegerField(default=0)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestures.presentationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="GestureLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                (
                    "gesture_type",
                    models.CharField(
                        choices=[
                            ("thumbs_up", "👍 Thumbs Up"),
                            ("fist", "✊ Fist"),
                            ("open_palm", "🖐️ Open Palm"),
                            ("victory", "✌️ Victory"),
                            ("ok", "👌 OK"),
                            ("unknown", "❓ Unknown"),
                        ],
                        max_length=50,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("frame_count", models.IntegerField(default=0)),
                ("hand_x", models.FloatField(blank=True, null=True)),
                ("hand_y", models.FloatField(blank=True, null=True)),
                ("hand_z", models.FloatField(blank=True, null=True)),
                ("detection_time_ms", models.FloatField(default=0.0)),
                ("frame_processing_time_ms", models.FloatField(default=0.0)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("user_agent", models.TextField(blank=True)),
                ("screen_resolution", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "created_at"],
                        name="gestures_ge_session_620d87_idx",
                    ),
                    models.Index(
                        fields=["gesture_type", "created_at"],
                        name="gestures_ge_gesture_4f89e8_idx",
                    ),
                ],
            },
        ),
    ]
