# Generated by Django 4.2.27 on 2026-03-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestures", "0002_presentationasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentationasset",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="presentationasset",
            index=models.Index(
                fields=["user", "is_favorite"], name="gestures_pr_user_id_ef9b9c_idx"
            ),
        ),
    ]
