# Generated by Django 4.2.27 on 2026-04-22 00:35

from django.db import migrations, models
import gestures.models


class Migration(migrations.Migration):

    dependencies = [
        ("gestures", "0006_rename_last_opened_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=gestures.models._user_avatar_upload_to
            ),
        ),
    ]
